### ISSUE TITLE
Add Yarn 2 in the benchmarks

### ISSUE THREAD

**Issue by hongbo-miao** [npm/benchmarks#26]
It would be great to compare with Yarn 2 in the benchmarks too. I think most people would be curious about the result. Thanks!
BTW, just switched yarn 1 to npm 7, it is so fast!

**Comment by darcyclarke** [comment]
@Hongbo-Miao not sure how to accurately portray Yarn v2 since it has taken a radically different approach. If you have ideas, feel free to open a PR that helps illustrate a fair way to compare it.

**Comment by Hongbo-Miao** [comment]
Yeah I know, I failed to onboard Yarn 2 last year when I tried. Not easy..

**Comment by fabioscsilva** [comment]
It would be worth it to have Yarn 2 (with PnP) and (without PnP)
